sudo: required

services:
  - docker

language: node_js

node_js:
  - "4"

env:
  matrix:
    - FACTORIO_VERSION=0.12.33

before_install:
  - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker pull "jjclark/factorio:${FACTORIO_VERSION}" || echo "ok"

script:
  - docker build -t "jjclark/factorio:${FACTORIO_VERSION}" .

after_success:
  - docker push "jjclark/factorio:${FACTORIO_VERSION}"
