sudo: required

services:
  - docker

language: node_js

node_js:
  - "4"

env:
  matrix:
    - FACTORIO_VERSION=0.14.5

before_install:
  - export PANEL_VERSION=$(node -e 'console.log(require("./package").version)')
  - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker pull "jjclark/factorio" || echo "ok"

script:
  - npm test
  - docker build -t "jjclark/factorio" .

after_success:
  - docker tag "jjclark/factorio" "jjclark/factorio:${FACTORIO_VERSION}"
  - docker push "jjclark/factorio:${FACTORIO_VERSION}"
  - docker push "jjclark/factorio"
